import { useState, useCallback } from "react";

const translations = {
  en: {
    appName:      "DONEFY",
    appSub:       "AI-Powered Productivity",
    tasks:        "Tasks",
    today:        "Today",
    upcoming:     "Upcoming",
    calendar:     "Calendar",
    completed:    "Completed",
    aiAssistant:  "AI Assistant",
    aiCapture:    "AI Capture",
    settings:     "Settings",
    addTask:      "Add task...",
    addBtn:       "Add",
    search:       "Search...",
    sortDate:     "By date",
    sortPriority: "By priority",
    sortAlpha:    "A–Z",
    high:         "High",
    medium:       "Medium",
    low:          "Low",
    done:         "Done",
    noTasks:      "No tasks found",
    dueDate:      "Due date",
    reminder:     "Reminder",
    reminderEmail:"Reminder email",
    notes:        "Notes",
    photo:        "Photo",
    deleteCompleted: "Delete completed",
    progress:     "completed",
    // AI
    aiCaptureTitle: "AI Task Capture",
    aiCaptureSub:   "Speak or type freely — AI will structure your tasks",
    aiCaptureReview:"tasks generated — review & edit before adding",
    speakOrType:    "e.g. \"Meeting with team tomorrow, finish report by Friday, buy groceries\"",
    sendToAI:       "Send to AI",
    analysingAI:    "AI is analysing...",
    clearText:      "Clear",
    backBtn:        "← Back",
    addAllBtn:      "Add all tasks",
    voiceHint:      "🎤 Click mic to speak · or type · Ctrl+Enter to send",
    goalPlaceholder:"e.g. Launch a blog...",
    suggestTasks:   "Suggest Tasks",
    prioritise:     "Prioritise",
    chatPlaceholder:"Ask anything...",
    // Settings
    theme:        "Theme",
    dark:         "Dark",
    light:        "Light",
    system:       "System",
    language:     "Language",
    aiProvider:   "AI Provider",
    activeProvider:"Active Provider",
    apiKey:       "API Key",
    model:        "Model",
    otherKeys:    "Set API keys for other providers",
    emailNotif:   "Email Notifications (SMTP)",
    smtpServer:   "SMTP Server",
    port:         "Port",
    emailAddress: "Email Address",
    password:     "Password / App Password",
    testEmail:    "Test Email",
    sendTest:     "Send Test",
    sending:      "Sending...",
    schedulerInterval: "Reminder check interval (seconds)",
    saveSettings: "Save Settings",
    saving:       "Saving...",
    saved:        "Settings saved ✓",
    // Calendar
    months:       ["January","February","March","April","May","June",
                   "July","August","September","October","November","December"],
    weekdays:     ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    tasksThisMonth: "tasks have due dates this month",
    // toasts
    taskAdded:    "Task added",
    taskDeleted:  "Task deleted",
    tasksAdded:   "tasks added",
    loadError:    "Failed to load tasks",
  },
  tr: {
    appName:      "DONEFY",
    appSub:       "Yapay Zeka Destekli Verimlilik",
    tasks:        "Görevler",
    today:        "Bugün",
    upcoming:     "Yaklaşan",
    calendar:     "Takvim",
    completed:    "Tamamlanan",
    aiAssistant:  "AI Asistan",
    aiCapture:    "AI Yakalama",
    settings:     "Ayarlar",
    addTask:      "Görev ekle...",
    addBtn:       "Ekle",
    search:       "Ara...",
    sortDate:     "Tarihe göre",
    sortPriority: "Önceliğe göre",
    sortAlpha:    "A–Z",
    high:         "Yüksek",
    medium:       "Orta",
    low:          "Düşük",
    done:         "Bitti",
    noTasks:      "Görev bulunamadı",
    dueDate:      "Son tarih",
    reminder:     "Hatırlatıcı",
    reminderEmail:"Hatırlatıcı e-posta",
    notes:        "Notlar",
    photo:        "Fotoğraf",
    deleteCompleted: "Tamamlananları sil",
    progress:     "tamamlandı",
    aiCaptureTitle: "AI Görev Yakalama",
    aiCaptureSub:   "Serbest konuş veya yaz — AI görevlerini yapılandırır",
    aiCaptureReview:"görev oluşturuldu — eklemeden önce düzenle",
    speakOrType:    "ör. \"Yarın toplantı var, raporu cumaya kadar bitir, market alışverişi\"",
    sendToAI:       "AI'ye Gönder",
    analysingAI:    "AI analiz ediyor...",
    clearText:      "Temizle",
    backBtn:        "← Geri",
    addAllBtn:      "Tüm görevleri ekle",
    voiceHint:      "🎤 Mikrofona tıkla · veya yaz · Ctrl+Enter ile gönder",
    goalPlaceholder:"ör. Blog yayınla...",
    suggestTasks:   "Görev Öner",
    prioritise:     "Önceliklendir",
    chatPlaceholder:"Bir şey sor...",
    theme:        "Tema",
    dark:         "Karanlık",
    light:        "Aydınlık",
    system:       "Sistem",
    language:     "Dil",
    aiProvider:   "AI Sağlayıcısı",
    activeProvider:"Aktif Sağlayıcı",
    apiKey:       "API Anahtarı",
    model:        "Model",
    otherKeys:    "Diğer sağlayıcıların API anahtarlarını ayarla",
    emailNotif:   "E-posta Bildirimleri (SMTP)",
    smtpServer:   "SMTP Sunucu",
    port:         "Port",
    emailAddress: "E-posta Adresi",
    password:     "Şifre / Uygulama Şifresi",
    testEmail:    "Test E-postası",
    sendTest:     "Test Gönder",
    sending:      "Gönderiliyor...",
    schedulerInterval: "Hatırlatıcı kontrol aralığı (saniye)",
    saveSettings: "Ayarları Kaydet",
    saving:       "Kaydediliyor...",
    saved:        "Ayarlar kaydedildi ✓",
    months:       ["Ocak","Şubat","Mart","Nisan","Mayıs","Haziran",
                   "Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"],
    weekdays:     ["Pzt","Sal","Çar","Per","Cum","Cmt","Paz"],
    tasksThisMonth: "görevin bu ay son tarihi var",
    taskAdded:    "Görev eklendi",
    taskDeleted:  "Görev silindi",
    tasksAdded:   "görev eklendi",
    loadError:    "Görevler yüklenemedi",
  }
};

export function useLang(initial = "en") {
  const [lang, setLang] = useState(initial);
  const t = useCallback((key) => translations[lang]?.[key] ?? translations.en[key] ?? key, [lang]);
  return { lang, setLang, t, translations };
}
